//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17914
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Data.Entity.Design.VisualStudio.SingleFileGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Data.Entity.Design.VisualStudio.SingleFileGenerator.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Generation failed for file &apos;{0}&apos;. Unable to find the conceptual model Schema element..
        /// </summary>
        internal static string CodeGenerationCannotFindElement {
            get {
                return ResourceManager.GetString("CodeGenerationCannotFindElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // T4 code generation is enabled for model &apos;{0}&apos;.
        ///// To enable legacy code generation, change the value of the &apos;Code Generation Strategy&apos; designer
        ///// property to &apos;Legacy ObjectContext&apos;. This property is available in the Properties Window when the model
        ///// is open in the designer.
        ///
        ///// If no context and entity classes have been generated, it may be because you created an empty model but
        ///// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
        ///// classes fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeGenerationDisabledCommentCSharp {
            get {
                return ResourceManager.GetString("CodeGenerationDisabledCommentCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; T4 code generation is enabled for model &apos;{0}&apos;.
        ///&apos; To enable legacy code generation, change the value of the &apos;Code Generation Strategy&apos; designer
        ///&apos; property to &apos;Legacy ObjectContext&apos;. This property is available in the Properties Window when the model
        ///&apos; is open in the designer.
        ///
        ///&apos; If no context and entity classes have been generated, it may be because you created an empty model but
        ///&apos; have not yet chosen which version of Entity Framework to use. To generate a context class and entity
        ///&apos; classes for your  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeGenerationDisabledCommentVB {
            get {
                return ResourceManager.GetString("CodeGenerationDisabledCommentVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Seeing this comment implies that the code generation for file &apos;{0}&apos;
        ///// failed. See the ErrorList for details..
        /// </summary>
        internal static string CodeGenerationFailureCommentCSharp {
            get {
                return ResourceManager.GetString("CodeGenerationFailureCommentCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; Seeing this comment implies that the code generation for file &apos;{0}&apos;
        ///&apos; failed. See the ErrorList for details..
        /// </summary>
        internal static string CodeGenerationFailureCommentVB {
            get {
                return ResourceManager.GetString("CodeGenerationFailureCommentVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to GetDefaultExtension() has failed because of the exception:.
        /// </summary>
        internal static string GetDefaultExtensionFailed {
            get {
                return ResourceManager.GetString("GetDefaultExtensionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not sited..
        /// </summary>
        internal static string ObjectNotSited {
            get {
                return ResourceManager.GetString("ObjectNotSited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site does not support the requested interface..
        /// </summary>
        internal static string SiteInterfaceNotSupported {
            get {
                return ResourceManager.GetString("SiteInterfaceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown or unsupported language. If this is a Web Site project, this probably means that the .edmx file is not under the App_Code directory..
        /// </summary>
        internal static string UnknownLanguage {
            get {
                return ResourceManager.GetString("UnknownLanguage", resourceCulture);
            }
        }
    }
}
