// <auto-generated />
namespace ConsoleTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class renamecolnametwo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamecolnametwo));
        
        string IMigrationMetadata.Id
        {
            get { return "202412190258050_renamecolnametwo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
