//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20402.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Data.Entity.Design.DataSourceWizardExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Data.Entity.Design.DataSourceWizardExtension.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model{0}.edmx.
        /// </summary>
        internal static string EdmDesignerFileNameFormat {
            get {
                return ResourceManager.GetString("EdmDesignerFileNameFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap EdmWizardIcon {
            get {
                object obj = ResourceManager.GetObject("EdmWizardIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of type &quot;{0}&quot; occurred while attempting to launch Entity Data Model Wizard. 
        ///The exception message is: 
        ///{1}.
        /// </summary>
        internal static string LaunchEntityDesignerWizardErrorMessage {
            get {
                return ResourceManager.GetString("LaunchEntityDesignerWizardErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching Entity Data Model Wizard, please wait ....
        /// </summary>
        internal static string LaunchingEntityDataModelWizardMessage {
            get {
                return ResourceManager.GetString("LaunchingEntityDataModelWizardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusLabel.
        /// </summary>
        internal static string StatusLabelAccessibleName {
            get {
                return ResourceManager.GetString("StatusLabelAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WizardEngineDescription {
            get {
                return ResourceManager.GetString("WizardEngineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Data Model.
        /// </summary>
        internal static string WizardEngineDisplayName {
            get {
                return ResourceManager.GetString("WizardEngineDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Data Model Wizard.
        /// </summary>
        internal static string WizardLaunchPageTitle {
            get {
                return ResourceManager.GetString("WizardLaunchPageTitle", resourceCulture);
            }
        }
    }
}
