//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Data.Entity.Design.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Data.Entity.Design.Model.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A diagram name must contain at least one non-whitespace character..
        /// </summary>
        internal static string BAD_DIAGRAM_NAME {
            get {
                return ResourceManager.GetString("BAD_DIAGRAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid enum member value..
        /// </summary>
        internal static string BadEnumTypeMemberValue {
            get {
                return ResourceManager.GetString("BadEnumTypeMemberValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} type is not valid..
        /// </summary>
        internal static string BadFunctionParameterType {
            get {
                return ResourceManager.GetString("BadFunctionParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item passed in is not a valid model item for this command..
        /// </summary>
        internal static string Command_InvalidModelItem {
            get {
                return ResourceManager.GetString("Command_InvalidModelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string ComplexPropertyUndefinedType {
            get {
                return ResourceManager.GetString("ComplexPropertyUndefinedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected a circular inheritance hierarchy containing entity type &apos;{0}&apos;..
        /// </summary>
        internal static string CyclicInheritanceHierarchy {
            get {
                return ResourceManager.GetString("CyclicInheritanceHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}::{1}.
        /// </summary>
        internal static string DatabaseColumnNameFormat {
            get {
                return ResourceManager.GetString("DatabaseColumnNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}::{1}.
        /// </summary>
        internal static string DatabaseObjectNameFormat {
            get {
                return ResourceManager.GetString("DatabaseObjectNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file contains DataServices element and cannot be opened in the Entity Designer..
        /// </summary>
        internal static string DataServicesNodeWarning {
            get {
                return ResourceManager.GetString("DataServicesNodeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        internal static string Default_Alias {
            get {
                return ResourceManager.GetString("Default_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated {0} element encountered..
        /// </summary>
        internal static string DuplicatedElementMsg {
            get {
                return ResourceManager.GetString("DuplicatedElementMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; can not be used for both the entity container name and the namespace name..
        /// </summary>
        internal static string EntityContainerNameConflictsWithNamespaceName {
            get {
                return ResourceManager.GetString("EntityContainerNameConflictsWithNamespaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the StoreGeneratedPattern facet on a property of enum type may cause a mismatch between the enum value of the property and the actual value inserted into the database..
        /// </summary>
        internal static string EnumPropertyHasNonEmptyStoreGeneratedPattern {
            get {
                return ResourceManager.GetString("EnumPropertyHasNonEmptyStoreGeneratedPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role name &apos;{0}&apos; is not valid because it is equal to the role name of the other association end within this association..
        /// </summary>
        internal static string Error_AssociationEndInAssocNotUnique {
            get {
                return ResourceManager.GetString("Error_AssociationEndInAssocNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a property of type {0} to this type – this would cause circular loop for this type definition..
        /// </summary>
        internal static string Error_CircularComplexTypeDefinitionOnAdd {
            get {
                return ResourceManager.GetString("Error_CircularComplexTypeDefinitionOnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change this property type to {0} – this would cause circular loop for the enclosing type definition..
        /// </summary>
        internal static string Error_CircularComplexTypeDefinitionOnChange {
            get {
                return ResourceManager.GetString("Error_CircularComplexTypeDefinitionOnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; is not unique in the &apos;{1}&apos; ComplexType..
        /// </summary>
        internal static string Error_ComplexTypePropertyNameNotUnique {
            get {
                return ResourceManager.GetString("Error_ComplexTypePropertyNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; is not unique in the &apos;{1}&apos; inheritance hierarchy..
        /// </summary>
        internal static string Error_MemberNameNotUnique {
            get {
                return ResourceManager.GetString("Error_MemberNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; cannot be used in type &apos;{1}&apos;. Member names cannot be the same as their enclosing type..
        /// </summary>
        internal static string Error_MemberNameSameAsParent {
            get {
                return ResourceManager.GetString("Error_MemberNameSameAsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name &apos;{0}&apos; is not valid. Please specify another name..
        /// </summary>
        internal static string Error_PropertyNameInvalid {
            get {
                return ResourceManager.GetString("Error_PropertyNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the conceptual model to validate..
        /// </summary>
        internal static string ErrorValidatingArtifact_ConceptualModelMissing {
            get {
                return ResourceManager.GetString("ErrorValidatingArtifact_ConceptualModelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML namespace for the conceptual model&apos;s Schema element is not supported on this Entity Framework schema version..
        /// </summary>
        internal static string ErrorValidatingArtifact_InvalidCSDLNamespaceForTargetFrameworkVersion {
            get {
                return ResourceManager.GetString("ErrorValidatingArtifact_InvalidCSDLNamespaceForTargetFrameworkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML namespace for the Mapping element is not supported on this Entity Framework schema version..
        /// </summary>
        internal static string ErrorValidatingArtifact_InvalidMSLNamespaceForTargetFrameworkVersion {
            get {
                return ResourceManager.GetString("ErrorValidatingArtifact_InvalidMSLNamespaceForTargetFrameworkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML namespace for the storage model&apos;s Schema element is not supported on this Entity Framework schema version..
        /// </summary>
        internal static string ErrorValidatingArtifact_InvalidSSDLNamespaceForTargetFrameworkVersion {
            get {
                return ResourceManager.GetString("ErrorValidatingArtifact_InvalidSSDLNamespaceForTargetFrameworkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the mapping model to validate..
        /// </summary>
        internal static string ErrorValidatingArtifact_MappingModelMissing {
            get {
                return ResourceManager.GetString("ErrorValidatingArtifact_MappingModelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the storage model to validate..
        /// </summary>
        internal static string ErrorValidatingArtifact_StorageModelMissing {
            get {
                return ResourceManager.GetString("ErrorValidatingArtifact_StorageModelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association &apos;{0}&apos; has no association set..
        /// </summary>
        internal static string EscherValidation_AssociationWithoutAssociationSet {
            get {
                return ResourceManager.GetString("EscherValidation_AssociationWithoutAssociationSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A circular complex type definition has been found for {0} complex type..
        /// </summary>
        internal static string EscherValidation_CircularComplexTypeDefinition {
            get {
                return ResourceManager.GetString("EscherValidation_CircularComplexTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A circular inheritance chain has been found involving entity types {0}..
        /// </summary>
        internal static string EscherValidation_CircularInheritance {
            get {
                return ResourceManager.GetString("EscherValidation_CircularInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComplexType elements are not supported in the Entity Designer..
        /// </summary>
        internal static string EscherValidation_ComplexTypesNotSupported {
            get {
                return ResourceManager.GetString("EscherValidation_ComplexTypesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type &apos;{0}&apos; has no entity set..
        /// </summary>
        internal static string EscherValidation_EntityTypesWithoutEntitySets {
            get {
                return ResourceManager.GetString("EscherValidation_EntityTypesWithoutEntitySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Association &apos;{0}&apos; is redundant: Its referential integrity constraint provides sufficient information.  You can safely delete the mapping information for this association..
        /// </summary>
        internal static string EscherValidation_IgnoreMappedFKAssociation {
            get {
                return ResourceManager.GetString("EscherValidation_IgnoreMappedFKAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type &apos;{0}&apos; exists in multiple entity sets: {1}..
        /// </summary>
        internal static string EscherValidation_MultipleEntitySetsPerType {
            get {
                return ResourceManager.GetString("EscherValidation_MultipleEntitySetsPerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of property {0} is undefined. A type must be provided for this property..
        /// </summary>
        internal static string EscherValidation_UndefinedComplexPropertyType {
            get {
                return ResourceManager.GetString("EscherValidation_UndefinedComplexPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association &apos;{0}&apos; is not mapped..
        /// </summary>
        internal static string EscherValidation_UnmappedAssociation {
            get {
                return ResourceManager.GetString("EscherValidation_UnmappedAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association End &apos;{0}&apos; is not mapped..
        /// </summary>
        internal static string EscherValidation_UnmappedAssociationEnd {
            get {
                return ResourceManager.GetString("EscherValidation_UnmappedAssociationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association End key property &apos;{0}&apos; is not mapped..
        /// </summary>
        internal static string EscherValidation_UnmappedAssociationEndKey {
            get {
                return ResourceManager.GetString("EscherValidation_UnmappedAssociationEndKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type &apos;{0}&apos; is not mapped..
        /// </summary>
        internal static string EscherValidation_UnmappedEntityType {
            get {
                return ResourceManager.GetString("EscherValidation_UnmappedEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is not mapped..
        /// </summary>
        internal static string EscherValidation_UnmappedProperty {
            get {
                return ResourceManager.GetString("EscherValidation_UnmappedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using elements are not supported in the Entity Designer..
        /// </summary>
        internal static string EscherValidation_UsingNotSupported {
            get {
                return ResourceManager.GetString("EscherValidation_UsingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of type &apos;{0}&apos; occurred while attempting to generate the database script from the model. The exception message is: &apos;{1}&apos;..
        /// </summary>
        internal static string GenerateDatabaseScriptExceptionMessage {
            get {
                return ResourceManager.GetString("GenerateDatabaseScriptExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitive type &apos;{0}&apos; is not a valid underlying type for an enum..
        /// </summary>
        internal static string Incorrect_Enum_UnderlyingType {
            get {
                return ResourceManager.GetString("Incorrect_Enum_UnderlyingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string INVALID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string INVALID_NC_NAME_CHAR {
            get {
                return ResourceManager.GetString("INVALID_NC_NAME_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string InvalidNamespaceName {
            get {
                return ResourceManager.GetString("InvalidNamespaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}.
        /// </summary>
        internal static string MappingModel_AliasDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_AliasDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (AssociationSet).
        /// </summary>
        internal static string MappingModel_AssociationSetMappingDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_AssociationSetMappingDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition on {0}.
        /// </summary>
        internal static string MappingModel_ConditionDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_ConditionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (DeleteFunction).
        /// </summary>
        internal static string MappingModel_DeleteFunctionDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_DeleteFunctionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (EndProperty).
        /// </summary>
        internal static string MappingModel_EndPropertyDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_EndPropertyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &lt;==&gt; {1}.
        /// </summary>
        internal static string MappingModel_EntityContainerMappingDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_EntityContainerMappingDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (EntitySet).
        /// </summary>
        internal static string MappingModel_EntitySetMappingDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_EntitySetMappingDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (EntityType).
        /// </summary>
        internal static string MappingModel_EntityTypeMappingDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_EntityTypeMappingDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}-&gt;{2} (AssociationEnd).
        /// </summary>
        internal static string MappingModel_FunctionAssociationEndDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_FunctionAssociationEndDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (InsertFunction).
        /// </summary>
        internal static string MappingModel_InsertFunctionDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_InsertFunctionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (TableName).
        /// </summary>
        internal static string MappingModel_MappingFragmentDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_MappingFragmentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificationFunctionMapping for {0}.
        /// </summary>
        internal static string MappingModel_ModificationFunctionMappingDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_ModificationFunctionMappingDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (UpdateFunction).
        /// </summary>
        internal static string MappingModel_UpdateFunctionDisplayName {
            get {
                return ResourceManager.GetString("MappingModel_UpdateFunctionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComplexType.
        /// </summary>
        internal static string Model_DefaultComplexTypeName {
            get {
                return ResourceManager.GetString("Model_DefaultComplexTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        internal static string Model_DefaultDiagramName {
            get {
                return ResourceManager.GetString("Model_DefaultDiagramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string Model_DefaultEntitySetSuffix {
            get {
                return ResourceManager.GetString("Model_DefaultEntitySetSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        internal static string Model_DefaultEntityTypeName {
            get {
                return ResourceManager.GetString("Model_DefaultEntityTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumType.
        /// </summary>
        internal static string Model_DefaultEnumTypeName {
            get {
                return ResourceManager.GetString("Model_DefaultEnumTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Model_IdPropertyName {
            get {
                return ResourceManager.GetString("Model_IdPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias elements require a Key attribute..
        /// </summary>
        internal static string ModelParse_AliasElementMissingKeyAttribute {
            get {
                return ResourceManager.GetString("ModelParse_AliasElementMissingKeyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias elements require a Value attribute..
        /// </summary>
        internal static string ModelParse_AliasElementMissingValueAttribute {
            get {
                return ResourceManager.GetString("ModelParse_AliasElementMissingValueAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; on element &apos;{1}&apos; is not supported by the EDM Designer..
        /// </summary>
        internal static string ModelParse_GhostNodeNotSupportedByDesigner {
            get {
                return ResourceManager.GetString("ModelParse_GhostNodeNotSupportedByDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; is only valid if the element does not have any &apos;{1}&apos; elements..
        /// </summary>
        internal static string ModelParse_MutuallyExclusiveAttributeAndChildElement {
            get {
                return ResourceManager.GetString("ModelParse_MutuallyExclusiveAttributeAndChildElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element &apos;{0}&apos; does not have the expected namespace value..
        /// </summary>
        internal static string ModelParse_NonQualifiedElement {
            get {
                return ResourceManager.GetString("ModelParse_NonQualifiedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name {0} cannot be duplicated in this context. Please choose another name..
        /// </summary>
        internal static string NAME_NOT_UNIQUE {
            get {
                return ResourceManager.GetString("NAME_NOT_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The suggested NavigationProperty name &apos;{0}&apos; cannot be the same as the name of the containing EntityType..
        /// </summary>
        internal static string NavPropNameSameAsContainer {
            get {
                return ResourceManager.GetString("NavPropNameSameAsContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; for the designer property &apos;{1}&apos; is not valid..
        /// </summary>
        internal static string NonValidDesignerProperty {
            get {
                return ResourceManager.GetString("NonValidDesignerProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires a consistent schema. Please validate schemas and fix all errors..
        /// </summary>
        internal static string OperationRequiresValidSchema {
            get {
                return ResourceManager.GetString("OperationRequiresValidSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A condition cannot be bound to a property and a column at the same time..
        /// </summary>
        internal static string RESOLVE_CONDITION_BOUND_TO_PROP_AND_COLUMN {
            get {
                return ResourceManager.GetString("RESOLVE_CONDITION_BOUND_TO_PROP_AND_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An alias element in the MSL references an unresolvable namespace &apos;{0}&apos;..
        /// </summary>
        internal static string RESOLVE_UNRESOLVED_ALIAS {
            get {
                return ResourceManager.GetString("RESOLVE_UNRESOLVED_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string SeparatorCharacterForMultipleItemsInAnErrorMessage {
            get {
                return ResourceManager.GetString("SeparatorCharacterForMultipleItemsInAnErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} cannot be used as a RowsAffectedParameter. The mode must be Out and the type must be convertible to integer - the parameter passed has mode {1} and type {2}.
        /// </summary>
        internal static string SetRowsAffectedParameterErrorMessage_CannotUse {
            get {
                return ResourceManager.GetString("SetRowsAffectedParameterErrorMessage_CannotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one Documentation element was declared. .
        /// </summary>
        internal static string TOO_MANY_DOCUMENTATION_ELEMENTS {
            get {
                return ResourceManager.GetString("TOO_MANY_DOCUMENTATION_ELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple EntityContainer elements were detected in namespace &apos;{0}&apos;..
        /// </summary>
        internal static string TOO_MANY_ENTITY_CONTAINER_ELEMENTS {
            get {
                return ResourceManager.GetString("TOO_MANY_ENTITY_CONTAINER_ELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one Key element was declared. .
        /// </summary>
        internal static string TOO_MANY_KEY_ELEMENTS {
            get {
                return ResourceManager.GetString("TOO_MANY_KEY_ELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ReferentialConstraint in the association named &apos;{0}&apos; is not valid. Multiple ReferentialConstraints are illegal for associations..
        /// </summary>
        internal static string TOO_MANY_REFERENTIAL_CONSTRAINTS_IN_ASSOCIATION {
            get {
                return ResourceManager.GetString("TOO_MANY_REFERENTIAL_CONSTRAINTS_IN_ASSOCIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected {0} element encountered..
        /// </summary>
        internal static string UnexpectedElementMsg {
            get {
                return ResourceManager.GetString("UnexpectedElementMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association type &apos;{0}&apos; has an undeclared association set or is malformed..
        /// </summary>
        internal static string UnresolvedAssociationSet_0 {
            get {
                return ResourceManager.GetString("UnresolvedAssociationSet_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base type &apos;{0}&apos; of entity type &apos;{1}&apos; is unresolved..
        /// </summary>
        internal static string UnresolvedBaseType_1 {
            get {
                return ResourceManager.GetString("UnresolvedBaseType_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type &apos;{0}&apos; has an undeclared entity set..
        /// </summary>
        internal static string UnresolvedEntitySet_0 {
            get {
                return ResourceManager.GetString("UnresolvedEntitySet_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved reference &apos;{0}&apos;..
        /// </summary>
        internal static string UnresolvedReference_0 {
            get {
                return ResourceManager.GetString("UnresolvedReference_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved referential constraint on association &apos;{0}&apos;..
        /// </summary>
        internal static string UnresolvedReferentialConstraint_0 {
            get {
                return ResourceManager.GetString("UnresolvedReferentialConstraint_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved type references {0} in EntityTypeMapping..
        /// </summary>
        internal static string UnresolvedTypeReferences_0 {
            get {
                return ResourceManager.GetString("UnresolvedTypeReferences_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Cannot resolve the target for AssociationEnd &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationEndNoTarget {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationEndNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to locate the navigation property for EntityType &apos;{0}&apos;, AssociationEnd &apos;{1}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationNoMatchingNavProp {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationNoMatchingNavProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to find database AssociationSetMapping for association &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationSetMappingCannotFind {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationSetMappingCannotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Cannot find the EntityType for property &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationSetMappingCannotFindEntityTypeForProperty {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationSetMappingCannotFindEntityTypeForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Within AssociationSetMapping, unable to clone scalar property &apos;{0}&apos;. Cannot find matching EntityType for database EntityType &apos;{1}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationSetMappingCannotFindMatchingEntityType {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationSetMappingCannotFindMatchingEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Within AssociationSetMapping, unable to clone scalar property &apos;{0}&apos;. Cannot find matching property for database property &apos;{1}&apos; in EntityType &apos;{2}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationSetMappingCannotFindMatchingProperty {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationSetMappingCannotFindMatchingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to find a matching storage EntitySet for the database EntitySet named &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationSetMappingCannotFindMatchingSSideEntitySet {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationSetMappingCannotFindMatchingSSideEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to clone scalar property &apos;{0}&apos; while processing an AssociationSetMapping. Cannot find a matching storage property for database storage property &apos;{1}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationSetMappingCannotFindMatchingSSideProperty {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationSetMappingCannotFindMatchingSSideProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to clone scalar property &apos;{0}&apos; while processing an AssociationSetMapping. Cannot find or create a matching property for the database property &apos;{1}&apos; in EntityType &apos;{2}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationSetMappingCannotFindOrCreateMatchingProperty {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationSetMappingCannotFindOrCreateMatchingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to clone scalar property &apos;{0}&apos; while processing an AssociationSetMapping. Cannot find a mapped storage property for conceptual property &apos;{1}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationSetMappingCannotFindSSideForCSideProperty {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationSetMappingCannotFindSSideForCSideProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to find database storage EntitySet for AssociationSetMapping &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationSetMappingCannotFindTempSSideEntitySet {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationSetMappingCannotFindTempSSideEntitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. AssociationSet &apos;{0}&apos; has an incorrect number of ends, &apos;{1}&apos;. There should be 2 ends..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationSetMappingWrongNumberAssociationSetEnds {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationSetMappingWrongNumberAssociationSetEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. The database AssociationSetMapping {0} has an incorrect number of ends, {1}. There should be 2 ends..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationSetMappingWrongNumberAssociationSetMappingEnds {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationSetMappingWrongNumberAssociationSetMappingEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. The database association &apos;{0}&apos; has an incorrect number of ends, {1}. There should be 2 ends..
        /// </summary>
        internal static string UpdateFromDatabaseAssociationWrongNumberEnds {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseAssociationWrongNumberEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to create a copy of database association &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseCannotCreateAssociation {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseCannotCreateAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to create an AssociationSetMapping based on the existing AssociationSet &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseCannotCreateAssociationSetMapping {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseCannotCreateAssociationSetMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to create an AssociationSetMapping EndProperty based on the existing AssociationSetEnd &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseCannotCreateAssociationSetMappingEndProperty {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseCannotCreateAssociationSetMappingEndProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to create an AssociationSetMapping based on the existing conceptual property &apos;{0}&apos; and the storage property &apos;{1}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseCannotCreateAssociationSetMappingScalarProperty {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseCannotCreateAssociationSetMappingScalarProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to create a copy of database EntityType &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseCannotCreateEntityType {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseCannotCreateEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. The attempt to add {0} new properties for DatabaseObject &apos;{1}&apos; failed. Cannot locate any matching root EntityType..
        /// </summary>
        internal static string UpdateFromDatabaseCannotFindRootEntityTypeForProperty {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseCannotFindRootEntityTypeForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Unable to clone the EntitySetMapping. Cannot find matching a EntityType for the database EntityType &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseEntitySetMappingCannotFindEntityType {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseEntitySetMappingCannotFindEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of type &apos;{0}&apos; occurred while attempting to update from the database. The exception message is: &apos;{1}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseExceptionMessage {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Cannot resolve the ColumnName Target for ScalarProperty &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseScalarPropertyNoColumnNameTarget {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseScalarPropertyNoColumnNameTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update from the database. Cannot resolve the Name Target for ScalarProperty &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateFromDatabaseScalarPropertyNoNameTarget {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseScalarPropertyNoNameTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The association &apos;{0}&apos; between the types in the model &apos;{1}&apos; and &apos;{2}&apos; was excluded because it had a referential constraint which referenced properties {3} which could not be found in those types..
        /// </summary>
        internal static string UpdateFromDatabaseUnableToBringRefConstraint {
            get {
                return ResourceManager.GetString("UpdateFromDatabaseUnableToBringRefConstraint", resourceCulture);
            }
        }
    }
}
