'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

#If Not NET40 Then
Partial Public Class MessageMm
    Public Property MessageId As Integer
    Public Property FromUsername As String
    Public Property ToUsername As String
    Public Property Sent As Date
    Public Property Subject As String
    Public Property Body As String
    Public Property IsRead As Boolean

    Public Overridable Property Sender As Another.Place.LoginMm
    Public Overridable Property Recipient As Another.Place.LoginMm

End Class
#End If
