'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

#If Not NET40 Then
Partial Public Class SupplierMm
    Public Property SupplierId As Integer
    Public Property Name As String

    Public Overridable Property Products As ICollection(Of ProductMm) = New HashSet(Of ProductMm)
    Public Overridable Property BackOrderLines As ICollection(Of BackOrderLineMm) = New HashSet(Of BackOrderLineMm)
    Public Overridable Property Logo As SupplierLogoMm

End Class
#End If
