//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionalTests.ProductivityApi.TemplateModels.CsMonsterModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageViewMm
    {
        public int PageViewId { get; set; }
        public string Username { get; set; }
        public System.DateTime Viewed { get; set; }
        public string PageUrl { get; set; }
    
        public virtual Another.Place.LoginMm Login { get; set; }
    }
}
