//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionalTests.ProductivityApi.TemplateModels.CsMonsterModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderQualityCheckMm
    {
        public int OrderId { get; set; }
        public string CheckedBy { get; set; }
        public System.DateTime CheckedDateTime { get; set; }
    
        public virtual OrderMm Order { get; set; }
    }
}
